// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Pzvm08gJTNs7Lr-YDBJ39H9StiRPxF0',
    appId: '1:56104911603:web:a0494aebc023bc02f32d86',
    messagingSenderId: '56104911603',
    projectId: 'mini-shopping-app-85a51',
    authDomain: 'mini-shopping-app-85a51.firebaseapp.com',
    storageBucket: 'mini-shopping-app-85a51.firebasestorage.app',
    measurementId: 'G-N7LN6CHF1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgFbZ6t_Gan22zB9xqkp5GXfKYVfc9jAg',
    appId: '1:56104911603:android:4954d4fbf0f0f7b9f32d86',
    messagingSenderId: '56104911603',
    projectId: 'mini-shopping-app-85a51',
    storageBucket: 'mini-shopping-app-85a51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaJ4rCrloQSP26zt7n0QKAMbYRTFg--HI',
    appId: '1:56104911603:ios:5e9b0042abcce2e8f32d86',
    messagingSenderId: '56104911603',
    projectId: 'mini-shopping-app-85a51',
    storageBucket: 'mini-shopping-app-85a51.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaJ4rCrloQSP26zt7n0QKAMbYRTFg--HI',
    appId: '1:56104911603:ios:5e9b0042abcce2e8f32d86',
    messagingSenderId: '56104911603',
    projectId: 'mini-shopping-app-85a51',
    storageBucket: 'mini-shopping-app-85a51.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Pzvm08gJTNs7Lr-YDBJ39H9StiRPxF0',
    appId: '1:56104911603:web:fd97a297c0e673bcf32d86',
    messagingSenderId: '56104911603',
    projectId: 'mini-shopping-app-85a51',
    authDomain: 'mini-shopping-app-85a51.firebaseapp.com',
    storageBucket: 'mini-shopping-app-85a51.firebasestorage.app',
    measurementId: 'G-S82ZKW10XV',
  );
}
